from enum import Enum, auto


class Difficulty(Enum):
    Easy        =   auto()
    Normal      =   auto()
    Hard        =   auto()
    Impossible  =   auto()




default_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}




allopew_pirate_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   6,
        'armor_class'       :   10,
        'custom_weapon'     :   (1, 4, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

allopew_raider_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   9,
        'armor_class'       :   11,
        'attack_bonus'      :   1,
        'proficiency'       :   1,
        'custom_weapon'     :   (2,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

allopew_buckaneer_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   15,
        'armor_class'       :   11,
        'attack_bonus'      :   1,
        'armor'             :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   1,
        'proficiency'       :   1,
        'custom_weapon'     :   (2,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


allopew_robber_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   14,
        'armor_class'       :   13,
        'attack_bonus'      :   1,
        'armor'             :   1,
        'evasion'           :   1,
        'crit_resist'       :   1,
        'proficiency'       :   1,
        'retaliation_chance':   1,
        'damage_bonus'      :   1,
        'custom_weapon'     :   (2,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

allopew_warlord_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   20,
        'armor_class'       :   12,
        'attack_bonus'      :   2,
        'armor'             :   1,
        'max_shields'       :   3,
        'shield_regen'      :   1,
        'crit_level'        :   1,
        'proficiency'       :   1,
        'damage_bonus'      :   1,
        'custom_weapon'     :   (2,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


allopew_captain_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   25,
        'armor_class'       :   13,
        'attack_bonus'      :   3,
        'armor'             :   1,
        'max_shields'       :   1,
        'shield_regen'      :   1,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'proficiency'       :   2,
        'retaliation_chance':   1,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

allopew_king_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   30,
        'armor_class'       :   13,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   (3, 4, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


prax_soldier_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   20,
        'armor_class'       :   14,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   1,
        'crit_resist'       :   None,
        'number_explosives' :   1,
        'ordinance_level'   :   1,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   2,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}



prax_lieutenant_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   24,
        'armor_class'       :   14,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   1,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

prax_captain_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   30,
        'armor_class'       :   14,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   2,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   1,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2, 6, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

prax_commando_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   30,
        'armor_class'       :   14,
        'attack_bonus'      :   3,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   2,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   2,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   4,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (3, 6, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

prax_specops_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   34,
        'armor_class'       :   14,
        'attack_bonus'      :   6,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   2,
        'evasion'           :   2,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   4,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2, 8, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


prex_oppressor_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   50,
        'armor_class'       :   13,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   3,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   1,
        'crit_resist'       :   2,
        'number_explosives' :   2,
        'ordinance_level'   :   2,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   1,
        'custom_weapon'     :   (2, 12, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

bethneki_drone_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   12,
        'armor_class'       :   12,
        'attack_bonus'      :   1,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   2,
        'shield_regen'      :   1,
        'evasion'           :   3,
        'crit_level'        :   1,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   1,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   (3,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

bethneki_robot_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   18,
        'armor_class'       :   12,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   2,
        'will'              :   None,
        'max_shields'       :   1,
        'shield_regen'      :   1,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   3,
        'ordinance_level'   :   1,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   1,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   (2,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

bethneki_scout_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   18,
        'armor_class'       :   14,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   4,
        'shield_regen'      :   2,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   2,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   (2,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


bethneki_researcher_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   25,
        'armor_class'       :   14,
        'attack_bonus'      :   1,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   2,
        'evasion'           :   1,
        'crit_level'        :   1,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   1,
        'custom_weapon'     :   (2,8,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

bethneki_guerrilla_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   30,
        'armor_class'       :   15,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   4,
        'shield_regen'      :   2,
        'evasion'           :   2,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   2,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   3,
        'retaliation_chance':   2,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (4,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

bethneki_assassin_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   30,
        'armor_class'       :   14,
        'attack_bonus'      :   3,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   4,
        'shield_regen'      :   2,
        'evasion'           :   3,
        'crit_level'        :   3,
        'crit_resist'       :   2,
        'number_explosives' :   3,
        'ordinance_level'   :   2,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   4,
        'retaliation_chance':   3,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


bethneki_mech_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   70,
        'armor_class'       :   13,
        'attack_bonus'      :   4,
        'weapon'            :   None,
        'armor'             :   3,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   3,
        'evasion'           :   None,
        'crit_level'        :   1,
        'crit_resist'       :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   3,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   4,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   3,
        'custom_weapon'     :   (4,6,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

ultranus_trooper_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   35,
        'armor_class'       :   14,
        'attack_bonus'      :   3,
        'weapon'            :   None,
        'armor'             :   1,
        'will'              :   None,
        'max_shields'       :   3,
        'shield_regen'      :   2,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   1,
        'number_explosives' :   1,
        'ordinance_level'   :   1,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   4,
        'retaliation_chance':   1,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (2, 6, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}


ultranus_stormtrooper_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   46,
        'armor_class'       :   14,
        'attack_bonus'      :   3,
        'weapon'            :   None,
        'armor'             :   2,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   3,
        'evasion'           :   None,
        'crit_level'        :   1,
        'crit_resist'       :   3,
        'number_explosives' :   2,
        'ordinance_level'   :   2,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   5,
        'retaliation_chance':   2,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   3,
        'custom_weapon'     :   (3, 4, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

ultranus_tank_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   95,
        'armor_class'       :   14,
        'attack_bonus'      :   5,
        'weapon'            :   None,
        'armor'             :   5,
        'will'              :   None,
        'max_shields'       :   5,
        'shield_regen'      :   2,
        'evasion'           :   None,
        'crit_level'        :   3,
        'crit_resist'       :   3,
        'number_explosives' :   2,
        'ordinance_level'   :   3,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   5,
        'retaliation_chance':   3,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   4,
        'custom_weapon'     :   (2, 10, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

void_thrall_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   6,
        'armor_class'       :   12,
        'attack_bonus'      :   2,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   3,
        'crit_level'        :   1,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   2,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   2,
        'custom_weapon'     :   (1,4,0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}

void_eater_dict = {
    Difficulty.Easy : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Normal : {
        'max_hit_points'    :   125,
        'armor_class'       :   17,
        'attack_bonus'      :   7,
        'weapon'            :   None,
        'armor'             :   5,
        'will'              :   None,
        'max_shields'       :   10,
        'shield_regen'      :   10,
        'evasion'           :   3,
        'crit_level'        :   3,
        'crit_resist'       :   3,
        'number_explosives' :   3,
        'ordinance_level'   :   3,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   6,
        'retaliation_chance':   3,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   7,
        'custom_weapon'     :   (3, 8, 0),
    },
    Difficulty.Hard : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
    Difficulty.Impossible : {
        'max_hit_points'    :   None,
        'armor_class'       :   None,
        'attack_bonus'      :   None,
        'weapon'            :   None,
        'armor'             :   None,
        'will'              :   None,
        'max_shields'       :   None,
        'shield_regen'      :   None,
        'evasion'           :   None,
        'crit_level'        :   None,
        'crit_resist'       :   None,
        'number_explosives' :   None,
        'ordinance_level'   :   None,
        'agro'              :   None,
        'cost'              :   None,
        'proficiency'       :   None,
        'retaliation_chance':   None,
        'hit_die_type'      :   None,
        'num_hit_dice'      :   None,
        'damage_bonus'      :   None,
        'custom_weapon'     :   None,
    },
}